<a href="https://colab.research.google.com/github/Lisawebdev/portfolio-website/blob/main/frauddetector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [7]:
df = pd.read_csv("fraudTest.csv", engine="python")

In [8]:
df

        Unnamed: 0 trans_date_trans_time  ...  merch_long is_fraud
0                0   2020-06-21 12:14:25  ...  -81.200714      0.0
1                1   2020-06-21 12:14:33  ... -109.960431      0.0
2                2   2020-06-21 12:14:53  ...  -74.196111      0.0
3                3   2020-06-21 12:15:15  ...  -80.883061      0.0
4                4   2020-06-21 12:15:17  ...  -85.884734      0.0
...            ...                   ...  ...         ...      ...
472875      472875   2020-12-13 21:55:15  ...  -86.113059      0.0
472876      472876   2020-12-13 21:55:16  ...  -94.805653      0.0
472877      472877   2020-12-13 21:55:16  ... -121.677340      0.0
472878      472878   2020-12-13 21:55:24  ...  -82.001533      0.0
472879      472879   2020-12-13 21:55:52  ...         NaN      NaN

[472880 rows x 23 columns]

In [10]:
df.head()

   Unnamed: 0 trans_date_trans_time  ...  merch_long is_fraud
0           0   2020-06-21 12:14:25  ...  -81.200714      0.0
1           1   2020-06-21 12:14:33  ... -109.960431      0.0
2           2   2020-06-21 12:14:53  ...  -74.196111      0.0
3           3   2020-06-21 12:15:15  ...  -80.883061      0.0
4           4   2020-06-21 12:15:17  ...  -85.884734      0.0

[5 rows x 23 columns]

In [12]:
df.shape

(472880, 23)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472880 entries, 0 to 472879
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             472880 non-null  int64
 1   trans_date_trans_time  472880 non-null  object
 2   cc_num                 472880 non-null  int64
 3   merchant               472880 non-null  object
 4   category               472880 non-null  object
 5   amt                    472880 non-null  float64
 6   first                  472880 non-null  object
 7   last                   472880 non-null  object
 8   gender                 472880 non-null  object
 9   street                 472880 non-null  object
 10  city                   472880 non-null  object
 11  state                  472880 non-null  object
 12  zip                    472880 non-null  int64
 13  lat                    472880 non-null  float64
 14  long                   472880 non-null  float64
 15  city_pop               472880 non-null  int64
 16  job                    472880 non-null  object
 17  dob                    472880 non-null  object
 18  trans_num              472880 non-null  object
 19  unix_time              472879 non-null  float64
 20  merch_lat              472879 non-null  float64
 21  merch_long             472879 non-null  float64
 22  is_fraud               472879 non-null  float64
dtypes: float64(7), int64(4), object(12)
memory usage: 83.0+ MB

In [14]:
df.describe()

          Unnamed: 0        cc_num  ...     merch_long       is_fraud
count  472880.000000  4.728800e+05  ...  472879.000000  472879.000000
mean   236439.500000  4.185844e+17  ...     -90.221251       0.004354
std    136508.841984  1.310978e+18  ...      13.733245       0.065842
min         0.000000  6.041621e+10  ...    -166.671575       0.000000
25%    118219.750000  1.800429e+14  ...     -96.895314       0.000000
50%    236439.500000  3.521417e+15  ...     -87.435847       0.000000
75%    354659.250000  4.642255e+15  ...     -80.254680       0.000000
max    472879.000000  4.992346e+18  ...     -66.952026       1.000000

[8 rows x 11 columns]

In [15]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                1
merch_lat                1
merch_long               1
is_fraud                 1
dtype: int64

In [16]:
df = df.dropna()

In [17]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [18]:
df['is_fraud'].value_counts()

is_fraud
0.0    470820
1.0      2059
Name: count, dtype: int64

In [19]:
df['is_fraud'].value_counts(normalize=True)

is_fraud
0.0    0.995646
1.0    0.004354
Name: proportion, dtype: float64

In [20]:
df.dtypes

Unnamed: 0                 int64
trans_date_trans_time     object
cc_num                     int64
merchant                  object
category                  object
amt                      float64
first                     object
last                      object
gender                    object
street                    object
city                      object
state                     object
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                       object
dob                       object
trans_num                 object
unix_time                float64
merch_lat                float64
merch_long               float64
is_fraud                 float64
dtype: object

In [23]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

print(num_cols)
print(cat_cols)

Index(['Unnamed: 0', 'cc_num', 'amt', 'zip', 'lat', 'long', 'city_pop',
       'unix_time', 'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')
Index(['trans_date_trans_time', 'merchant', 'category', 'first', 'last',
       'gender', 'street', 'city', 'state', 'job', 'dob', 'trans_num'],
      dtype='object')

In [24]:
for col in cat_cols:
    print(f"{col}: {df[col].nunique()} unique values")

trans_date_trans_time: 464335 unique values
merchant: 693 unique values
category: 14 unique values
first: 341 unique values
last: 471 unique values
gender: 2 unique values
street: 923 unique values
city: 848 unique values
state: 50 unique values
job: 478 unique values
dob: 909 unique values
trans_num: 472879 unique values

In [26]:
df.columns

Index(['cc_num', 'merchant', 'category', 'amt', 'gender', 'city', 'state',
       'zip', 'lat', 'long', 'city_pop', 'job', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [36]:
df = df.drop(columns=[
    "Unnamed: 0",
    "trans_date_trans_time",
    "first",
    "last",
    "street",
    "dob",
    "zip",
    'trans_num'
])

In [37]:
df.columns

Index(['cc_num', 'merchant', 'category', 'amt', 'gender', 'city', 'state',
       'lat', 'long', 'city_pop', 'job', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud'],
      dtype='object')

In [38]:
# Feature engineering

In [39]:
df.columns.to_list()

['cc_num',
 'merchant',
 'category',
 'amt',
 'gender',
 'city',
 'state',
 'lat',
 'long',
 'city_pop',
 'job',
 'unix_time',
 'merch_lat',
 'merch_long',
 'is_fraud']

In [41]:
cat_cols = df.select_dtypes(include="object").columns
print(cat_cols)

Index(['merchant', 'category', 'gender', 'city', 'state', 'job'], dtype='object')

In [44]:
# changing categorical values into numerical values
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [45]:
df.head()

             cc_num  merchant  category  ...  merch_lat  merch_long  is_fraud
0  2291163933867244       319        10  ...  33.986391  -81.200714       0.0
1  3573030041201292       591        10  ...  39.450498 -109.960431       0.0
2  3598215285024754       611         5  ...  40.495810  -74.196111       0.0
3  3591919803438423       222         9  ...  28.812398  -80.883061       0.0
4  3526826139003047       292        13  ...  44.959148  -85.884734       0.0

[5 rows x 15 columns]

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 472879 entries, 0 to 472878
Data columns (total 15 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   cc_num      472879 non-null  int64
 1   merchant    472879 non-null  int64
 2   category    472879 non-null  int64
 3   amt         472879 non-null  float64
 4   gender      472879 non-null  int64
 5   city        472879 non-null  int64
 6   state       472879 non-null  int64
 7   lat         472879 non-null  float64
 8   long        472879 non-null  float64
 9   city_pop    472879 non-null  int64
 10  job         472879 non-null  int64
 11  unix_time   472879 non-null  float64
 12  merch_lat   472879 non-null  float64
 13  merch_long  472879 non-null  float64
 14  is_fraud    472879 non-null  float64
dtypes: float64(7), int64(8)
memory usage: 57.7 MB

In [49]:
df['is_fraud'] = df['is_fraud'].astype(int)

In [50]:
df.head()

             cc_num  merchant  category  ...  merch_lat  merch_long  is_fraud
0  2291163933867244       319        10  ...  33.986391  -81.200714         0
1  3573030041201292       591        10  ...  39.450498 -109.960431         0
2  3598215285024754       611         5  ...  40.495810  -74.196111         0
3  3591919803438423       222         9  ...  28.812398  -80.883061         0
4  3526826139003047       292        13  ...  44.959148  -85.884734         0

[5 rows x 15 columns]

In [85]:
X = df.drop(['is_fraud', 'cc_num'], axis = 1)
y = df['is_fraud']

In [86]:
print(X.shape)
print(y.shape)

(472879, 13)
(472879,)

In [87]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(378303, 14)
(94576, 14)
(378303,)
(94576,)

In [88]:
# model selection

In [89]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [90]:
print(y_train.value_counts())

is_fraud
0    376656
1      1647
Name: count, dtype: int64

In [91]:
print(y_test.value_counts())

is_fraud
0    94164
1      412
Name: count, dtype: int64

In [92]:
# feature scaling

In [93]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [94]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

In [95]:
print(y_train.value_counts())

is_fraud
0    376656
1      1647
Name: count, dtype: int64

In [96]:
print(y_train_smote.value_counts())

is_fraud
0    376656
1    376656
Name: count, dtype: int64

In [97]:
# train the ML model using classification

In [98]:
#model import
from sklearn.linear_model import LogisticRegression

In [99]:
#model creation
model = LogisticRegression(random_state=42, max_iter=1000)

In [100]:
#model training
model.fit(X_train_smote, y_train_smote)

LogisticRegression(max_iter=1000, random_state=42)

In [101]:
#making prediction
y_pred = model.predict(X_test)

In [102]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score

In [103]:
print("Accuracy: ",accuracy_score(y_test, y_pred))
print("Precision: ",precision_score(y_test, y_pred))
print("Recall: ",recall_score(y_test, y_pred))
print("F1 Score: ",f1_score(y_test, y_pred))

Accuracy:  0.9404077144307224
Precision:  0.05258650222679
Recall:  0.7451456310679612
F1 Score:  0.09824

In [104]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[88633  5531]
 [  105   307]]

In [105]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97     94164
           1       0.05      0.75      0.10       412

    accuracy                           0.94     94576
   macro avg       0.53      0.84      0.53     94576
weighted avg       0.99      0.94      0.97     94576

In [108]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs = -1)
rf.fit(X_train_smote, y_train_smote)